import type { AppLocale } from "../../lib/i18n";
import type { SkillOperationsCopy } from "./SkillOperationsPage.types";

const copy: SkillOperationsCopy = {
  refresh: "Refresh",
  liveState: "Live backend data",
  schedulerEnabled: "Scheduler enabled",
  schedulerDisabled: "Scheduler disabled",
  requestFailed: "Request failed",
  policySaved: "Repository sync policy saved",
  sourceInventory: "Source Inventory",
  sourceType: "Source",
  visibility: "Visibility",
  updatedAt: "Updated",
  owner: "Owner",
  noRuns: "No sync runs were returned for the current selection.",
  runID: "Run ID",
  runStatus: "Status",
  runScope: "Scope",
  runTrigger: "Trigger",
  jobType: "Job Type",
  actor: "Actor",
  createdAt: "Created",
  targetSkill: "Target Skill",
  runStartedAt: "Started",
  runFailed: "Failed",
  runSynced: "Synced",
  selectedRunDetail: "Selected Run Detail",
  detailPayload: "Detail Payload",
  policyTitle: "Repository Sync Policy",
  policyDescription: "Repository routes keep scheduler control and run evidence visible from the same workbench.",
  batchSize: "Batch Size",
  interval: "Interval",
  timeout: "Timeout",
  enabled: "Enabled",
  savePolicy: "Save Policy",
  actions: "Actions",
  openSkills: "Open Skills",
  openImports: "Open Imports",
  openSyncRuns: "Open Sync Runs",
  retryAction: "Retry",
  cancelAction: "Cancel",
  formHints: {
    manual: "Create a manual skill directly from authored content.",
    repository: "Clone a repository, extract metadata, and store a repository-backed skill.",
    archive: "Upload a packaged archive and let the backend extract content.",
    skillmp: "Import a remote SkillMP package into the governed inventory."
  },
  manual: {
    title: "Manual Ingestion",
    subtitle: "Author a governed skill entry without leaving the standardized admin workbench.",
    eyebrow: "Skill Operations",
    primaryActionLabel: "Create Manual Skill",
    inventoryTitle: "Manual Skills",
    inventoryEmptyText: "No manual skills are available yet.",
    name: "Name",
    description: "Description",
    content: "Content",
    tags: "Tags",
    installCommand: "Install Command",
    submit: "Create Manual Skill"
  },
  repository: {
    title: "Repository Ingestion",
    subtitle: "Onboard a repository-backed skill while keeping sync evidence and policy in view.",
    eyebrow: "Skill Operations",
    primaryActionLabel: "Sync Repository Skill",
    inventoryTitle: "Repository Skills",
    inventoryEmptyText: "No repository-backed skills are available yet.",
    repoURL: "Repository URL",
    repoBranch: "Branch",
    repoPath: "Path",
    tags: "Tags",
    installCommand: "Install Command",
    submit: "Sync Repository Skill",
    runBatchSync: "Run Repository Sync",
    latestRuns: "Latest Sync Runs"
  },
  imports: {
    title: "Import Center",
    subtitle: "Run archive and SkillMP imports from one admin workbench instead of separate prototype pages.",
    eyebrow: "Skill Operations",
    primaryActionLabel: "Import Archive",
    inventoryTitle: "Imported Skills",
    inventoryEmptyText: "No imported skills are available yet.",
    archiveTitle: "Import Archive",
    archiveFile: "Archive File",
    archiveSubmit: "Import Archive",
    skillmpTitle: "Import SkillMP",
    skillmpURL: "SkillMP URL",
    skillmpID: "SkillMP ID",
    skillmpToken: "SkillMP Token",
    skillmpSubmit: "Import SkillMP",
    jobsTitle: "Import Jobs",
    jobsEmptyText: "No import jobs are available yet."
  },
  syncRuns: {
    title: "Sync Runs",
    subtitle: "Inspect repository synchronization history and keep the scheduler contract editable beside the ledger.",
    eyebrow: "Skill Operations",
    primaryActionLabel: "Refresh Runs",
    inventoryTitle: "Sync Runs",
    inventoryEmptyText: "No sync runs were returned yet.",
    refreshRuns: "Refresh Runs",
    latestRuns: "Latest Sync Runs"
  }
};

export function getSkillOperationsCopy(locale: AppLocale): SkillOperationsCopy {
  void locale;
  return copy;
}
