import type { TFunction } from "i18next";

export interface MarketplaceText {
  brandTitle: string;
  brandSubtitle: string;
  signedOut: string;
  statsMain: string;
  statsSub: string;
  statsPromo: string;
  statsTrendLabel: string;
  statsDeltaLeft: string;
  statsDeltaRight: string;
  signedIn: string;
  signIn: string;
  signOut: string;
  openWorkspace: string;
  categoryNav: string;
  downloadRankingNav: string;
  curatedTitle: string;
  installableLabel: string;
  verifiedLabel: string;
  updatedLabel: string;
  pressHintLabel: string;
  latestTitle: string;
  resultsTitle: string;
  categoryResultsTitle: string;
  latestSortLabel: string;
  batchInstallLabel: string;
  compareLabel: string;
  paginationMeta: string;
  keywordPrefix: string;
  semanticPrefix: string;
  queryKeyword: string;
  querySemantic: string;
  queryPlaceholder: string;
  semanticPlaceholder: string;
  search: string;
  advanced: string;
  hotkeyLabel: string;
  allCategories: string;
  allSubcategories: string;
  sortRecent: string;
  sortStars: string;
  sortQuality: string;
  modeKeyword: string;
  modeAI: string;
  resetFilters: string;
  hotAutomation: string;
  hotRepository: string;
  hotRelease: string;
  recommendedLabel: string;
  modeLabel: string;
  sortLabel: string;
  viewLabel: string;
  queueLabel: string;
  openQueue: string;
  resultsModalTitle: string;
  resultsClose: string;
  resultsModalKeywordPlaceholder: string;
  resultsModalSemanticPlaceholder: string;
  resultsFilter: string;
  resultsShortcutHint: string;
  resultsFooterLeftTemplate: string;
  resultsFooterRight: string;
  resultsStatMatchedTemplate: string;
  resultsStatLatency: string;
  resultsCardMetaTagsLabel: string;
  resultsCardMetaScoreLabel: string;
  resultsCardMetaUpdatedLabel: string;
  resultsCardAction: string;
  loadMore: string;
  loadMoreHint: string;
  loadMoreLoadingHint: string;
  loadMoreSuccessHint: string;
  loadMoreFinishedTitle: string;
  loadMoreFinishedHint: string;
  noResultsTitle: string;
  noResultsHint: string;
  previous: string;
  next: string;
}

export function buildMarketplaceText(t: TFunction): MarketplaceText {
  return {
    brandTitle: t("marketplace.brandTitle"),
    brandSubtitle: t("marketplace.brandSubtitle"),
    signedOut: t("marketplace.signedOut"),
    statsMain: t("marketplace.statsMain"),
    statsSub: t("marketplace.statsSub"),
    statsPromo: t("marketplace.statsPromo"),
    statsTrendLabel: t("marketplace.statsTrendLabel"),
    statsDeltaLeft: t("marketplace.statsDeltaLeft"),
    statsDeltaRight: t("marketplace.statsDeltaRight"),
    signedIn: t("marketplace.signedIn"),
    signIn: t("marketplace.signIn"),
    signOut: t("marketplace.signOut"),
    openWorkspace: t("marketplace.openWorkspace"),
    categoryNav: t("marketplace.categoryNav"),
    downloadRankingNav: t("marketplace.downloadRankingNav"),
    curatedTitle: t("marketplace.curatedTitle"),
    installableLabel: t("marketplace.installableLabel"),
    verifiedLabel: t("marketplace.verifiedLabel"),
    updatedLabel: t("marketplace.updatedLabel"),
    pressHintLabel: t("marketplace.pressHintLabel"),
    latestTitle: t("marketplace.latestTitle"),
    resultsTitle: t("marketplace.resultsTitle"),
    categoryResultsTitle: t("marketplace.categoryResultsTitle"),
    latestSortLabel: t("marketplace.latestSortLabel"),
    batchInstallLabel: t("marketplace.batchInstallLabel"),
    compareLabel: t("marketplace.compareLabel"),
    paginationMeta: t("marketplace.paginationMeta"),
    keywordPrefix: t("marketplace.keywordPrefix"),
    semanticPrefix: t("marketplace.semanticPrefix"),
    queryKeyword: t("marketplace.queryKeyword"),
    querySemantic: t("marketplace.querySemantic"),
    queryPlaceholder: t("marketplace.queryPlaceholder"),
    semanticPlaceholder: t("marketplace.semanticPlaceholder"),
    search: t("marketplace.search"),
    advanced: t("marketplace.advanced"),
    hotkeyLabel: t("marketplace.hotkeyLabel"),
    allCategories: t("marketplace.allCategories"),
    allSubcategories: t("marketplace.allSubcategories"),
    sortRecent: t("marketplace.sortRecent"),
    sortStars: t("marketplace.sortStars"),
    sortQuality: t("marketplace.sortQuality"),
    modeKeyword: t("marketplace.modeKeyword"),
    modeAI: t("marketplace.modeAI"),
    resetFilters: t("marketplace.resetFilters"),
    hotAutomation: t("marketplace.hotAutomation"),
    hotRepository: t("marketplace.hotRepository"),
    hotRelease: t("marketplace.hotRelease"),
    recommendedLabel: t("marketplace.recommendedLabel"),
    modeLabel: t("marketplace.modeLabel"),
    sortLabel: t("marketplace.sortLabel"),
    viewLabel: t("marketplace.viewLabel"),
    queueLabel: t("marketplace.queueLabel"),
    openQueue: t("marketplace.openQueue"),
    resultsModalTitle: t("marketplace.resultsModalTitle"),
    resultsClose: t("marketplace.resultsClose"),
    resultsModalKeywordPlaceholder: t("marketplace.resultsModalKeywordPlaceholder"),
    resultsModalSemanticPlaceholder: t("marketplace.resultsModalSemanticPlaceholder"),
    resultsFilter: t("marketplace.resultsFilter"),
    resultsShortcutHint: t("marketplace.resultsShortcutHint"),
    resultsFooterLeftTemplate: t("marketplace.resultsFooterLeftTemplate"),
    resultsFooterRight: t("marketplace.resultsFooterRight"),
    resultsStatMatchedTemplate: t("marketplace.resultsStatMatchedTemplate"),
    resultsStatLatency: t("marketplace.resultsStatLatency"),
    resultsCardMetaTagsLabel: t("marketplace.resultsCardMetaTagsLabel"),
    resultsCardMetaScoreLabel: t("marketplace.resultsCardMetaScoreLabel"),
    resultsCardMetaUpdatedLabel: t("marketplace.resultsCardMetaUpdatedLabel"),
    resultsCardAction: t("marketplace.resultsCardAction"),
    loadMore: t("marketplace.loadMore"),
    loadMoreHint: t("marketplace.loadMoreHint"),
    loadMoreLoadingHint: t("marketplace.loadMoreLoadingHint"),
    loadMoreSuccessHint: t("marketplace.loadMoreSuccessHint"),
    loadMoreFinishedTitle: t("marketplace.loadMoreFinishedTitle"),
    loadMoreFinishedHint: t("marketplace.loadMoreFinishedHint"),
    noResultsTitle: t("marketplace.noResultsTitle"),
    noResultsHint: t("marketplace.noResultsHint"),
    previous: t("marketplace.previous"),
    next: t("marketplace.next")
  };
}
