import { buildPathWithQuery } from "./ConsoleWorkbench";
import { asNumber, asObject } from "./AdminWorkbenchDefinitionHelpers";
import type { AdminOpsRoute } from "./AdminWorkbenchTypes";
import type { WorkbenchDefinition } from "./ConsoleWorkbench";

export const adminWorkbenchOpsDefinitions: Record<AdminOpsRoute, WorkbenchDefinition> = {
  "/admin/ops/metrics": {
    title: "Operations Metrics",
    subtitle: "Latency, throughput, error rates, and sync health baseline.",
    resources: [
      {
        key: "metrics",
        title: "Metrics Snapshot",
        description: "Current operations metrics generated by backend service.",
        buildPath: () => "/api/v1/admin/ops/metrics"
      }
    ],
    summary: (resources) => {
      const payload = asObject(resources.metrics);
      const item = asObject(payload.item);
      return [
        { label: "Request QPS", value: asNumber(item.request_qps) },
        { label: "Latency P95 (ms)", value: asNumber(item.latency_p95_ms) },
        { label: "Sync Success", value: asNumber(item.sync_success_rate) },
        { label: "Failed Syncs 24h", value: asNumber(item.failed_sync_runs_24h) }
      ];
    }
  },
  "/admin/ops/alerts": {
    title: "Operations Alerts",
    subtitle: "Derived alerts from reliability and governance thresholds.",
    resources: [
      {
        key: "alerts",
        title: "Alert Snapshot",
        description: "Read current alert set and severity distribution.",
        buildPath: () => "/api/v1/admin/ops/alerts"
      }
    ],
    summary: (resources) => {
      const payload = asObject(resources.alerts);
      const items = Array.isArray(payload.items) ? payload.items : [];
      const triggered = items.filter((item) => Boolean(asObject(item).triggered)).length;
      return [
        { label: "Total Alerts", value: asNumber(payload.total) },
        { label: "Triggered", value: triggered }
      ];
    }
  },
  "/admin/ops/audit-export": {
    title: "Audit Export",
    subtitle: "Query audit export payload in JSON window for compliance checks.",
    resources: [
      {
        key: "auditExport",
        title: "Audit Export JSON",
        description: "Use RFC3339 timestamps or date-only values.",
        fields: [
          { key: "from", label: "From", type: "text", placeholder: "2026-01-01 or 2026-01-01T00:00:00Z" },
          { key: "to", label: "To", type: "text", placeholder: "2026-01-31 or 2026-01-31T23:59:59Z" },
          {
            key: "format",
            label: "Format",
            type: "select",
            defaultValue: "json",
            options: [{ label: "json", value: "json" }]
          }
        ],
        buildPath: (values) => buildPathWithQuery("/api/v1/admin/ops/audit-export", values)
      }
    ]
  },
  "/admin/ops/release-gates": {
    title: "Release Gates",
    subtitle: "Review gate checks and trigger on-demand gate run.",
    resources: [
      {
        key: "releaseGates",
        title: "Release Gate Snapshot",
        buildPath: () => "/api/v1/admin/ops/release-gates"
      }
    ],
    actions: [
      {
        key: "runReleaseGates",
        title: "Run Release Gates",
        description: "Execute gate checks and persist audit evidence.",
        submitText: "Run",
        buildPath: () => "/api/v1/admin/ops/release-gates/run",
        refreshResources: ["releaseGates"]
      }
    ]
  },
  "/admin/ops/recovery-drills": {
    title: "Recovery Drills",
    subtitle: "Track RPO/RTO drill results and append new evidence.",
    resources: [
      {
        key: "recoveryDrills",
        title: "Recovery Drill Records",
        fields: [{ key: "limit", label: "Limit", type: "number", defaultValue: 20, min: 1, max: 100 }],
        buildPath: (values) => buildPathWithQuery("/api/v1/admin/ops/recovery-drills", values)
      }
    ],
    actions: [
      {
        key: "recordRecoveryDrill",
        title: "Record Drill",
        description: "Submit one drill run with optional note and explicit timestamp.",
        submitText: "Create Record",
        fields: [
          { key: "rpo_hours", label: "RPO Hours", type: "number", required: true, min: 0.1, step: 0.1 },
          { key: "rto_hours", label: "RTO Hours", type: "number", required: true, min: 0.1, step: 0.1 },
          { key: "note", label: "Note", type: "textarea", placeholder: "Optional context" },
          { key: "occurred_at", label: "Occurred At", type: "text", placeholder: "RFC3339 or YYYY-MM-DD" }
        ],
        buildPath: () => "/api/v1/admin/ops/recovery-drills/run",
        refreshResources: ["recoveryDrills"]
      }
    ]
  },
  "/admin/ops/releases": {
    title: "Release Timeline",
    subtitle: "List release records and create new release entries.",
    resources: [
      {
        key: "releases",
        title: "Release Records",
        fields: [{ key: "limit", label: "Limit", type: "number", defaultValue: 20, min: 1, max: 100 }],
        buildPath: (values) => buildPathWithQuery("/api/v1/admin/ops/releases", values)
      }
    ],
    actions: [
      {
        key: "createRelease",
        title: "Create Release Record",
        submitText: "Create",
        fields: [
          { key: "version", label: "Version", type: "text", required: true, placeholder: "v1.2.3" },
          {
            key: "environment",
            label: "Environment",
            type: "select",
            required: true,
            defaultValue: "production",
            options: [
              { label: "production", value: "production" },
              { label: "staging", value: "staging" },
              { label: "preview", value: "preview" }
            ]
          },
          { key: "change_ticket", label: "Change Ticket", type: "text", placeholder: "CHG-123" },
          { key: "status", label: "Status", type: "text", placeholder: "success, partial, failed" },
          { key: "note", label: "Note", type: "textarea" },
          { key: "released_at", label: "Released At", type: "text", placeholder: "RFC3339 or YYYY-MM-DD" }
        ],
        buildPath: () => "/api/v1/admin/ops/releases",
        refreshResources: ["releases"]
      }
    ]
  },
  "/admin/ops/change-approvals": {
    title: "Change Approvals",
    subtitle: "Track change governance decisions and reviewer outcomes.",
    resources: [
      {
        key: "changeApprovals",
        title: "Change Approval Records",
        fields: [{ key: "limit", label: "Limit", type: "number", defaultValue: 20, min: 1, max: 100 }],
        buildPath: (values) => buildPathWithQuery("/api/v1/admin/ops/change-approvals", values)
      }
    ],
    actions: [
      {
        key: "createChangeApproval",
        title: "Create Approval Record",
        submitText: "Create",
        fields: [
          { key: "ticket_id", label: "Ticket ID", type: "text", required: true, placeholder: "CHG-234" },
          { key: "reviewer", label: "Reviewer", type: "text", placeholder: "reviewer username" },
          {
            key: "status",
            label: "Status",
            type: "select",
            defaultValue: "approved",
            options: [
              { label: "approved", value: "approved" },
              { label: "pending", value: "pending" },
              { label: "rejected", value: "rejected" }
            ]
          },
          { key: "note", label: "Note", type: "textarea" },
          { key: "occurred_at", label: "Occurred At", type: "text", placeholder: "RFC3339 or YYYY-MM-DD" }
        ],
        buildPath: () => "/api/v1/admin/ops/change-approvals",
        refreshResources: ["changeApprovals"]
      }
    ]
  },
  "/admin/ops/backup/plans": {
    title: "Backup Plans",
    subtitle: "Manage backup plan policies and retention configuration.",
    resources: [
      {
        key: "backupPlans",
        title: "Backup Plan Records",
        fields: [{ key: "limit", label: "Limit", type: "number", defaultValue: 20, min: 1, max: 100 }],
        buildPath: (values) => buildPathWithQuery("/api/v1/admin/ops/backup/plans", values)
      }
    ],
    actions: [
      {
        key: "upsertBackupPlan",
        title: "Create or Update Backup Plan",
        submitText: "Upsert",
        fields: [
          { key: "plan_key", label: "Plan Key", type: "text", required: true, placeholder: "daily-core" },
          {
            key: "backup_type",
            label: "Backup Type",
            type: "select",
            required: true,
            defaultValue: "full",
            options: [
              { label: "full", value: "full" },
              { label: "incremental", value: "incremental" },
              { label: "snapshot", value: "snapshot" }
            ]
          },
          { key: "schedule", label: "Schedule", type: "text", required: true, placeholder: "0 */6 * * *" },
          { key: "retention_days", label: "Retention Days", type: "number", required: true, min: 1, max: 3650 },
          { key: "enabled", label: "Enabled", type: "switch", defaultValue: true },
          { key: "note", label: "Note", type: "textarea" },
          { key: "occurred_at", label: "Occurred At", type: "text", placeholder: "RFC3339 or YYYY-MM-DD" }
        ],
        buildPath: () => "/api/v1/admin/ops/backup/plans",
        refreshResources: ["backupPlans"]
      }
    ]
  },
  "/admin/ops/backup/runs": {
    title: "Backup Runs",
    subtitle: "Capture backup execution status with size and duration evidence.",
    resources: [
      {
        key: "backupRuns",
        title: "Backup Run Records",
        fields: [{ key: "limit", label: "Limit", type: "number", defaultValue: 20, min: 1, max: 100 }],
        buildPath: (values) => buildPathWithQuery("/api/v1/admin/ops/backup/runs", values)
      }
    ],
    actions: [
      {
        key: "createBackupRun",
        title: "Create Backup Run",
        submitText: "Create",
        fields: [
          { key: "plan_key", label: "Plan Key", type: "text", required: true, placeholder: "daily-core" },
          {
            key: "status",
            label: "Status",
            type: "select",
            defaultValue: "success",
            options: [
              { label: "success", value: "success" },
              { label: "warning", value: "warning" },
              { label: "failed", value: "failed" }
            ]
          },
          { key: "size_mb", label: "Size MB", type: "number", min: 0, step: 0.1 },
          { key: "duration_minutes", label: "Duration Minutes", type: "number", min: 0, step: 0.1 },
          { key: "note", label: "Note", type: "textarea" },
          { key: "occurred_at", label: "Occurred At", type: "text", placeholder: "RFC3339 or YYYY-MM-DD" }
        ],
        buildPath: () => "/api/v1/admin/ops/backup/runs",
        refreshResources: ["backupRuns"]
      }
    ]
  }
};
