package web

import "github.com/go-chi/chi/v5"

func (a *App) registerAuthenticatedRoutes(r chi.Router) {
	r.Group(func(authRoutes chi.Router) {
		authRoutes.Use(a.requireAuth)
		authRoutes.Get("/account", a.handleAccountRoot)
		authRoutes.Get("/account/profile", a.handleAccountProfile)
		authRoutes.Post("/account/profile", a.handleAccountProfileUpdate)
		authRoutes.Get("/account/security", a.handleAccountSecurity)
		authRoutes.Get("/account/api-credentials", a.handleAccountAPICredentials)
		authRoutes.Post("/account/security/password", a.handleAccountPasswordUpdate)
		authRoutes.Get("/account/sessions", a.handleAccountSessions)
		authRoutes.Post("/account/sessions/{sessionID}/revoke", a.handleAccountSessionRevoke)
		authRoutes.Post("/account/sessions/revoke-others", a.handleAccountSessionsRevokeOthers)
		authRoutes.Get("/api/v1/account/profile", a.handleAPIAccountProfile)
		authRoutes.Get("/api/v1/account/apikeys", a.handleAPIAccountAPIKeys)
		authRoutes.Post("/api/v1/account/apikeys", a.handleAPIAccountAPIKeysCreate)
		authRoutes.Post("/api/v1/account/apikeys/{keyID}/revoke", a.handleAPIAccountAPIKeyRevoke)
		authRoutes.Post("/api/v1/account/apikeys/{keyID}/rotate", a.handleAPIAccountAPIKeyRotate)
		authRoutes.Post("/api/v1/account/apikeys/{keyID}/scopes", a.handleAPIAccountAPIKeyScopesUpdate)
		authRoutes.Post("/api/v1/account/profile", a.handleAPIAccountProfileUpdate)
		authRoutes.Post("/api/v1/account/security/password", a.handleAPIAccountPasswordUpdate)
		authRoutes.Get("/api/v1/account/sessions", a.handleAPIAccountSessions)
		authRoutes.Post("/api/v1/account/sessions/{sessionID}/revoke", a.handleAPIAccountSessionRevoke)
		authRoutes.Post("/api/v1/account/sessions/revoke-others", a.handleAPIAccountSessionsRevokeOthers)
		authRoutes.Get("/api/v1/dingtalk/me", a.handleDingTalkMe)
		authRoutes.Post("/auth/dingtalk/revoke", a.handleDingTalkRevoke)
		authRoutes.Post("/api/v1/skills/{skillID}/report", a.handleAPISkillReport)
		authRoutes.Post("/api/v1/skills/{skillID}/comments/{commentID}/report", a.handleAPICommentReport)
		authRoutes.Post("/api/v1/skills/{skillID}/favorite", a.handleAPISkillFavorite)
		authRoutes.Post("/api/v1/skills/{skillID}/rating", a.handleAPISkillRating)
		authRoutes.Post("/api/v1/skills/{skillID}/comments", a.handleAPISkillCommentCreate)
		authRoutes.Post("/api/v1/skills/{skillID}/comments/{commentID}/delete", a.handleAPISkillCommentDelete)
		authRoutes.Get("/api/v1/skills/{skillID}/sync-runs", a.handleAPISkillSyncRuns)
		authRoutes.Get("/api/v1/skills/{skillID}/sync-runs/{runID}", a.handleAPISkillSyncRunDetail)
		authRoutes.Get("/api/v1/skills/{skillID}/versions", a.handleAPISkillVersions)
		authRoutes.Get("/api/v1/skills/{skillID}/versions/{versionID}", a.handleAPISkillVersionDetail)
		authRoutes.Post("/api/v1/skills/{skillID}/organization-bind", a.handleAPISkillOrganizationBind)
		authRoutes.Post("/api/v1/skills/{skillID}/organization-unbind", a.handleAPISkillOrganizationUnbind)
		authRoutes.Post("/skills/{skillID}/organization-bind", a.handleSkillOrganizationBind)
		authRoutes.Post("/skills/{skillID}/organization-unbind", a.handleSkillOrganizationUnbind)
		authRoutes.Post("/skills/{skillID}/favorite", a.handleSkillFavorite)
		authRoutes.Post("/skills/{skillID}/rating", a.handleSkillRating)
		authRoutes.Post("/skills/{skillID}/comments", a.handleSkillCommentCreate)
		authRoutes.Post("/skills/{skillID}/comments/{commentID}/delete", a.handleSkillCommentDelete)
	})
}
