package web

import "testing"

func TestBuildOpenAPISpecContainsCorePaths(t *testing.T) {
	spec := buildOpenAPISpec("http://127.0.0.1:8080")

	if got, ok := spec["openapi"].(string); !ok || got == "" {
		t.Fatalf("missing openapi version")
	}

	paths, ok := spec["paths"].(map[string]any)
	if !ok {
		t.Fatalf("missing paths object")
	}

	requiredPaths := []string{
		"/api/v1/public/marketplace",
		"/api/v1/public/rankings",
		"/api/v1/public/skills/{skillID}",
		"/api/v1/public/skills/compare",
		"/api/v1/public/skills/{skillID}/resources",
		"/api/v1/public/skills/{skillID}/resource-file",
		"/api/v1/public/skills/{skillID}/versions",
		"/api/v1/skills/search",
		"/api/v1/skills/ai-search",
		"/api/v1/auth/login",
		"/api/v1/auth/providers",
		"/api/v1/auth/csrf",
		"/api/v1/auth/me",
		"/api/v1/auth/logout",
		"/api/v1/account/profile",
		"/api/v1/account/apikeys",
		"/api/v1/account/apikeys/{keyID}/revoke",
		"/api/v1/account/apikeys/{keyID}/rotate",
		"/api/v1/account/apikeys/{keyID}/scopes",
		"/api/v1/account/password-reset/request",
		"/api/v1/account/password-reset/confirm",
		"/api/v1/account/security/password",
		"/api/v1/account/sessions",
		"/api/v1/account/sessions/{sessionID}/revoke",
		"/api/v1/account/sessions/revoke-others",
		"/api/v1/dingtalk/me",
		"/auth/sso/start/{provider}",
		"/auth/sso/callback/{provider}",
		"/api/v1/admin/overview",
		"/api/v1/admin/skills",
		"/api/v1/admin/skills/{skillID}/sync",
		"/api/v1/admin/skills/{skillID}/visibility",
		"/api/v1/admin/skills/{skillID}/delete",
		"/api/v1/admin/api-management/specs/current",
		"/api/v1/admin/api-management/specs/import",
		"/api/v1/admin/api-management/specs/{specID}/validate",
		"/api/v1/admin/api-management/specs/{specID}/publish",
		"/api/v1/admin/api-management/specs/current/export.json",
		"/api/v1/admin/api-management/specs/current/export.yaml",
		"/api/v1/admin/api-management/exports",
		"/api/v1/admin/api-management/operations",
		"/api/v1/admin/api-management/operations/{operationID}/policy",
		"/api/v1/admin/api-management/mock/profiles",
		"/api/v1/admin/api-management/mock/profiles/{profileID}/overrides",
		"/api/v1/admin/api-management/mock/profiles/{profileID}/overrides/{operationID}",
		"/api/v1/admin/api-management/mock/resolve",
		"/api/v1/admin/ingestion/manual",
		"/api/v1/admin/ingestion/upload",
		"/api/v1/admin/ingestion/repository",
		"/api/v1/admin/ingestion/skillmp",
		"/api/v1/admin/integrations",
		"/api/v1/admin/jobs",
		"/api/v1/admin/jobs/{jobID}",
		"/api/v1/admin/jobs/{jobID}/retry",
		"/api/v1/admin/jobs/{jobID}/cancel",
		"/api/v1/admin/sync-jobs",
		"/api/v1/admin/sync-jobs/{runID}",
		"/api/v1/admin/sync-runs",
		"/api/v1/admin/sync-runs/{runID}",
		"/api/v1/admin/sync-policy/repository",
		"/api/v1/admin/sync-policies",
		"/api/v1/admin/sync-policies/{policyID}",
		"/api/v1/admin/sync-policies/create",
		"/api/v1/admin/sync-policies/{policyID}/update",
		"/api/v1/admin/sync-policies/{policyID}/toggle",
		"/api/v1/admin/sync-policies/{policyID}/delete",
		"/api/v1/admin/ops/metrics",
		"/api/v1/admin/ops/alerts",
		"/api/v1/admin/ops/audit-export",
		"/api/v1/admin/ops/release-gates",
		"/api/v1/admin/ops/release-gates/run",
		"/api/v1/admin/ops/recovery-drills",
		"/api/v1/admin/ops/recovery-drills/run",
		"/api/v1/admin/ops/releases",
		"/api/v1/admin/ops/change-approvals",
		"/api/v1/admin/ops/backup/plans",
		"/api/v1/admin/ops/backup/runs",
		"/api/v1/admin/apikeys",
		"/api/v1/admin/apikeys/{keyID}",
		"/api/v1/admin/apikeys/{keyID}/revoke",
		"/api/v1/admin/apikeys/{keyID}/rotate",
		"/api/v1/admin/apikeys/{keyID}/scopes",
		"/api/v1/admin/sso/providers",
		"/api/v1/admin/sso/providers/{providerID}/disable",
		"/api/v1/admin/sso/users/sync",
		"/api/v1/admin/settings/registration",
		"/api/v1/admin/settings/marketplace-ranking",
		"/api/v1/admin/settings/presentation-taxonomy",
		"/api/v1/admin/settings/auth-providers",
		"/api/v1/admin/accounts",
		"/api/v1/admin/user-center/accounts",
		"/api/v1/admin/user-center/sync",
		"/api/v1/admin/user-center/permissions/{userID}",
		"/api/v1/admin/users/{userID}/role",
		"/api/v1/admin/accounts/{userID}/status",
		"/api/v1/admin/accounts/{userID}/force-signout",
		"/api/v1/admin/accounts/{userID}/password-reset",
		"/api/v1/admin/organizations",
		"/api/v1/admin/organizations/{orgID}/members",
		"/api/v1/admin/organizations/{orgID}/members/{userID}/role",
		"/api/v1/admin/organizations/{orgID}/members/{userID}/remove",
		"/api/v1/admin/moderation",
		"/api/v1/admin/moderation/{caseID}/resolve",
		"/api/v1/admin/moderation/{caseID}/reject",
		"/api/v1/skills/{skillID}/report",
		"/api/v1/skills/{skillID}/comments/{commentID}/report",
		"/api/v1/skills/{skillID}/favorite",
		"/api/v1/skills/{skillID}/rating",
		"/api/v1/skills/{skillID}/comments",
		"/api/v1/skills/{skillID}/comments/{commentID}/delete",
		"/api/v1/skills/{skillID}/sync-runs",
		"/api/v1/skills/{skillID}/sync-runs/{runID}",
		"/api/v1/skills/{skillID}/organization-bind",
		"/api/v1/skills/{skillID}/organization-unbind",
		"/api/v1/skills/{skillID}/versions",
		"/api/v1/skills/{skillID}/versions/{versionID}",
		"/api/v1/skills/{skillID}/versions/{versionID}/rollback",
		"/api/v1/skills/{skillID}/versions/{versionID}/restore",
		"/skills/{skillID}/versions",
		"/skills/{skillID}/versions/{versionID}",
		"/skills/{skillID}/versions/compare",
		"/skills/{skillID}/versions/{versionID}/rollback",
		"/skills/{skillID}/favorite",
		"/skills/{skillID}/rating",
		"/skills/{skillID}/comments",
		"/skills/{skillID}/comments/{commentID}/delete",
		"/skills/{skillID}/organization-bind",
		"/skills/{skillID}/organization-unbind",
		"/admin/apikeys/create",
		"/admin/apikeys/{keyID}/revoke",
		"/admin/apikeys/{keyID}/rotate",
		"/admin/users/{userID}/role",
		"/admin/sso/providers/create",
		"/admin/sso/providers/{providerID}/disable",
		"/admin/sso/users/sync",
	}
	for _, path := range requiredPaths {
		if _, exists := paths[path]; !exists {
			t.Fatalf("missing required path in openapi spec: %s", path)
		}
	}
}
